### ISSUE TITLE
[FEATURE] Expand ActionMenu when clicked plus block action button 

### ISSUE THREAD

**Issue by Darginec05** [Darginec05/Yoopta-Editor#129]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

-

### Proposed Solution

-

### Do you want to work on this issue?

Yes

### If "yes" to the above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

If ActionMenu is in tools it should listen event and show menu in right place

**Comment by Darginec05** [comment]
Fixed in [v4.1.0](https://github.com/Darginec05/Yoopta-Editor/releases/tag/v4.1.0)

**Comment by niraj-khatiwada** [comment]
@Darginec05 is there a way to programmatically open the action menu? My requirement is when user presses the "Enter" key on a new block and if the block is empty, I need to prompt user to select the block type for which I need to trigger the action menu. I figured out the keyboarding handling part but couldn't figure out how to open action menu programmatically.
I also tried setting the block content to "/" hoping that it'll trigger the menu via shortcut but doesn't seem to work.
Thanks for the awesome library.

```
import { PluginEvents } from '@yoopta/editor/dist/plugins/types'

export const events: Partial<PluginEvents> = {
  onKeyDown: (editor, _, options) => {
    return evt => {
      // Block entering new line when text is empty and trigger the action list.
      if (options.hotkeys.isEnter(evt)) {
        if (
          'children' in options?.currentBlock?.value?.[0] &&
          'text' in options?.currentBlock?.value?.[0]?.children?.[0]
        ) {
          const text = options?.currentBlock?.value?.[0]?.children?.[0]?.text as string
          if (text?.length === 0) {
            evt.preventDefault()
            // TODO: Need to trigger the action menu.
          }
        }
      }
    }
  },
}
```

**Comment by Bumang-Cyber** [comment]
it still doesn't expand ActionMenu when clicking Plus button in my case.
I did all same with the example in official docs.


```
import ActionMenuList, {
  DefaultActionMenuRender,
} from "@yoopta/action-menu-list";

// ...

const TOOLS = {
  ActionMenuList: {
    render: DefaultActionMenuRender,
    tool: ActionMenuList,
  },
  Toolbar: {
    render: DefaultToolbarRender,
    tool: Toolbar,
  },
  LinkTool: {
    tool: LinkTool,
    render: DefaultLinkToolRender,
  },
};

// ...

  return (
      <YooptaEditor
        width="100%"
        className="flex-1 p-2"
        editor={editor}
        plugins={plugins}
        placeholder="Type Something Cool..."
        value={editorValue}
        onChange={onChangeEditorValue}
        selectionBoxRoot={selectionRef}
        tools={TOOLS} // TOOLS are embeded here.
        marks={MARKS}
        autoFocus
        readOnly={readOnly}
      />
```

```
"@yoopta/action-menu-list": "^4.9.7",
"@yoopta/editor": "^4.9.7",
// ... rest of all is also on 4.9.7
```

**Comment by Darginec05** [comment]
@Bumang-Cyber rechecked it, works fine.
Could you please record video and send it here?

**Comment by Bumang-Cyber** [comment]
https://github.com/user-attachments/assets/86d9227b-cb2a-4155-894e-fda41f09cd51

as you can see, '/' shortcut works fine.
but the plus button adds only new line without showing actionMenu.
I've followed your demos code. but mine doesn't show actionMenu.
thanks for your fast responding. 

```typescript
"use client";

import YooptaEditor, {
  SlateElement,
  YooptaContentValue,
  YooptaPlugin,
  Blocks,
  YooEditor,
} from "@yoopta/editor";

import {
  Bold,
  Italic,
  CodeMark,
  Underline,
  Strike,
  Highlight,
} from "@yoopta/marks";

import ActionMenuList, {
  DefaultActionMenuRender,
} from "@yoopta/action-menu-list";
import Toolbar, { DefaultToolbarRender } from "@yoopta/toolbar";
import LinkTool, { DefaultLinkToolRender } from "@yoopta/link-tool";

import Paragraph from "@yoopta/paragraph";
import Blockquote from "@yoopta/blockquote";
import Embed from "@yoopta/embed";
import Image, { ImageElementProps } from "@yoopta/image";
import Link from "@yoopta/link";
import Callout from "@yoopta/callout";
import Video from "@yoopta/video";
import File from "@yoopta/file";
import Accordion from "@yoopta/accordion";
import { NumberedList, BulletedList, TodoList } from "@yoopta/lists";

import { HeadingOne, HeadingThree, HeadingTwo } from "@yoopta/headings";
import Code from "@yoopta/code";
import Table from "@yoopta/table";
import Divider from "@yoopta/divider";
import { useRef } from "react";

const plugins = [
  Paragraph,
  Table,
  Divider.extend({
    elementProps: {
      divider: (props) => ({
        ...props,
        color: "#007aff",
      }),
    },
  }),
  Accordion,
  HeadingOne,
  HeadingTwo,
  HeadingThree,
  Blockquote,
  Callout.extend({
    options: {
      shortcuts: ["<"],
    },
  }),
  NumberedList,
  BulletedList,
  TodoList,
  Code.extend({
    options: {
      shortcuts: ["\`\`\`"],
    },
  }),
  Link,
  Embed,
  Image.extend({
    elementProps: {
      image: (props: ImageElementProps) => ({
        ...props,
        alt: "S3",
        fit: "contain",
      }),
    },
    options: {
      async onUpload(file) {

        // const data = await uploadToCloudinary(file, 'image');
        // return {
        //   src: data.secure_url,
        //   alt: "cloudinary",
        //   sizes: {
        //     width: data.width,
        //     height: data.height,
        //   },
        // };
        return {};
      },
    },
  }),
  Video,
  // .extend({
  // options: {
  //   onUpload: async (file) => {
  //     const data = await uploadToCloudinary(file, 'video');
  //     return {
  //       src: data.secure_url,
  //       alt: 'cloudinary',
  //       sizes: {
  //         width: data.width,
  //         height: data.height,
  //       },
  //     };
  //   },
  //   onUploadPoster: async (file) => {
  //     const image = await uploadToCloudinary(file, 'image');
  //     return image.secure_url;
  //   },
  // },
  // })
  File,
  // .extend({
  // options: {
  //   onUpload: async (file) => {
  //     const response = await uploadToCloudinary(file, 'auto');
  //     return { src: response.secure_url, format: response.format, name: response.name, size: response.bytes };
  //   },
  // },
  // }),
] as YooptaPlugin<Record<string, SlateElement>, Record<string, unknown>>[];

const MARKS = [Bold, Italic, CodeMark, Underline, Strike, Highlight];

const TOOLS = {
  ActionMenuList: {
    render: DefaultActionMenuRender,
    tool: ActionMenuList,
  },
  Toolbar: {
    render: DefaultToolbarRender,
    tool: Toolbar,
  },
  LinkTool: {
    tool: LinkTool,
    render: DefaultLinkToolRender,
  },
};

interface EditorProps {
  editor: YooEditor;
  editorValue: YooptaContentValue | undefined;

  onChangeEditorValue: (value: YooptaContentValue) => void;
  readOnly?: boolean;
}

const Editor = ({
  readOnly = false,
  editor,
  editorValue,
  onChangeEditorValue,
}: EditorProps) => {
  const selectionRef = useRef<HTMLDivElement>(null);

  const addBlockData = (index: number, focus = true) => {
    if (readOnly) return;

    const blockData = Blocks.buildBlockData();
    const insertBlockOptions = {
      blockData,
      at: index,
      focus,
    };
    const insertedId = editor.insertBlock("Paragraph", insertBlockOptions);

    return insertedId;
  };

  const handleEditorFocus = () => {
    if (selectionRef.current) {
      if (editor.isEmpty()) {
        addBlockData(0, true);
      } else {
        const length = Object.keys(editor.getEditorValue()).length;
        if (length <= 20) {
          addBlockData(length, false);
        }
      }
    }
  };

  return (
    <div
      className="flex flex-1 flex-col"
      ref={selectionRef}
      onClick={handleEditorFocus}
    >
      <YooptaEditor
        width="100%"
        className="flex-1 p-2"
        editor={editor}
        plugins={plugins}
        placeholder="Type Something Fine..."
        value={editorValue}
        onChange={onChangeEditorValue}
        selectionBoxRoot={selectionRef}
        tools={TOOLS}
        marks={MARKS}
        autoFocus
        readOnly={readOnly}
      />
    </div>
  );
};

export default Editor;
```
